### ISSUE TITLE
Axes qui évoluent dans deux dimensions.

### ISSUE THREAD

**Issue by adrienpacifico** [adrienpacifico/openfisca-france-notebook-story#1]
### Problème
Pour produire un heatmap donnant par exemple le gain fiscal au mariage en fonction du salaire des deux conjoints il faut faire varier le salaire de chacun des conjoints.
#### Mauvaise pratique
Pour faire cela on peut créer un axe qui fait varier le salaire du premier conjoint en "vectoriel" et construire une boucle "python" lente et moche qui fait varier le salaire du deuxième conjoint.

### Meilleure solution ?
Faire marcher les axes dans deux dimensions.
Ça implique je suppose de faire un array n^n fois plus long (devient vite très gros ?).

@benjello où faut-il bidouiller en premier ?

**Comment by benjello** [comment]
@adrienpacifico : n²

**Comment by adrienpacifico** [comment]
@benjello  Tu as raison, j'ai fait une erreur, c'est bien n2. 
Tu aurais une solution/des conseils pour faire varier les axes dans deux dimension ?

**Comment by benjello** [comment]
@adrienpacifico : il faut utiliser une liste pour l'argument axes pour avoir des axes perpendiculaires. Et une liste de listes pour avoir des axes parallèles. Voir https://github.com/openfisca/openfisca-core/blob/master/tests/core/test_axes.py pour des exemples d'axes parallèles (pas de tests d'axes perpendiculaires).

**Comment by adrienpacifico** [comment]
Ah, je vais essayer ! Merci (j'étais en train de faire directement un générateur de test case customisé, mais ça commençait à devenir un peu compliqué pour moi).

**Comment by adrienpacifico** [comment]
Ça fonctionne très bien, je m'en suis servi pour faire un [heatmap](http://htmlpreview.github.io/?https://github.com/adrienpacifico/adrienpacifico.github.io/blob/dev/Notebooks/cohabitants-heatmap.html) de toutes les allocations possible pour un couple de conjoints avec enfants. Merci !
